# Generated by Django 4.2.7 on 2023-11-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('story_name', models.CharField(max_length=255)),
                ('file', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(max_length=50)),
                ('mp3_file', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
